name: Deploy Supabase Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase CLI
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase login --access-token $SUPABASE_ACCESS_TOKEN

      - name: Set SERVICE_ROLE_KEY secret (if provided)
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}
        run: |
          if [ -n "$SERVICE_ROLE_KEY" ]; then
            supabase secrets set SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY" --project-ref $SUPABASE_PROJECT_REF
          else
            echo "SERVICE_ROLE_KEY not provided as secret; skipping secret set"
          fi

      - name: Deploy functions
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy hybrid-search --project-ref $SUPABASE_PROJECT_REF
          supabase functions deploy process-file --project-ref $SUPABASE_PROJECT_REF
